### ISSUE TITLE
Will this be updated ?

### ISSUE THREAD

**Issue by insert3coins** [MagicMau/EliteJournalReader#2]
Hi just wondering if there's an update in progress?

Cheers :)

**Comment by MagicMau** [comment]
yup, working to be compatible with all the new events from the 3.0 version. I've pushed the work in progress to branch features/journal_3.0 if you want to get a head start. 
However it's not yet fully tested and reading status.json does not work yet, so please bear with me while I'm ironing out the kinks. :)

**Comment by insert3coins** [comment]
Thank you very very much :)
