### ISSUE TITLE
Event updates

### ISSUE THREAD

**Issue by Norca** [MagicMau/EliteJournalReader#5]
Not really an issue just some missing fields in a couple of events;

Event MaterialCollectedEventArgs is missing a string called Name_Localised
Event MiningRefinedEventArgs is missing a string called Type_Localised

**Comment by Norca** [comment]
Found another one;

Event MissionCompletedEventArgs is missing a string called Commodity_Localised

**Comment by MagicMau** [comment]
Thanks @Norca, I've updated the code to add the missing types.
