### ISSUE TITLE
Missing (unnecessary?) source file

### ISSUE THREAD

**Issue by TechInterMezzo** [MagicMau/EliteJournalReader#7]
"EliteG19s\SharedAssemblyInfo.cs" doesn't seem to be part of the project.

https://github.com/MagicMau/EliteJournalReader/blob/eed0e5d17b6b8d0dd4f2929c59fc4df8e3dcb887/EliteJournalReader/EliteJournalReader.csproj#L103

Compilation fails because of that entry.

**Comment by MagicMau** [comment]
You are absolutely right. I have removed the link to the shared file.
