### ISSUE TITLE
More a question than an issue

### ISSUE THREAD

**Issue by Tim-Otte** [MagicMau/EliteJournalReader#8]
Dear @MagicMau,

I like your little masterpiece you created here. I have only one question: Is there an event for the landing gear (deployed, retracted)? I couldn't find this event in the event list...

**Comment by MagicMau** [comment]
Thanks Tim! Unfortunately, no such event exists.

However, there is a StatusWatcher that you can enable to react to changes to the file status.json. Whenever that file changes during play, a new StatusFileEvent is triggered, which contains a property Flags.
You can test these flags to see if the landing gear is down:

`StatusFlags.HasFlag(StatusFlags.LandingGearDown)`

Hope that helps!

**Comment by Tim-Otte** [comment]
Thank you for your reply. I will test my code this weekend...

Keep up the good work 👍
