### ISSUE TITLE
read mission details from previous sessions

### ISSUE THREAD

**Issue by TechInterMezzo** [MagicMau/EliteJournalReader#9]
Is it possible to read active mission details like the needed amount of cargo from previous sessions? It looks like the missions.json file doesn`t provide this info.  It`s only part of new mission events.

**Comment by MagicMau** [comment]
I've checked the docs provided by Frontier (https://forums.frontier.co.uk/showthread.php/452937-Journal-Docs-for-v3-3), but it doesn't seem that this information is available. You will need to track the Mission events while they happen I think.

I would also recommend you to check with the EDCD Discord (https://edcd.github.io/), it's very much possible that one of the third party devs already has come up with a nice solution for this.
